# Dependencies
markdown: kramdown
# markdown:         redcarpet
# highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Brian Kim
tagline:          'Aspiring programmer'
description:      'while(!succeed) try();'
url:              http://briank621.github.io
baseurl:          /

author:
  name:           'Brian Kim'
  url:             http://briank621.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://briank621.github.io

plugins:
  - jekyll-paginate
